### ISSUE TITLE
Please don't do things like this

### ISSUE THREAD

**Issue by codingonHP** [IndianBoy42/hop.nvim#6]
https://twitter.com/RosaCtrl/status/1451825921544097794

**Comment by IndianBoy42** [comment]
I didn't post saying that, or that it is unmaintained. I do agree that that is not a great look. I posted once saying that i helped integrate some features on my own. And I am more than willing to merge this back not that the og maintainer has returned.

https://www.reddit.com/r/neovim/comments/pqfi8k/hop_around_treesitter_nodes/

I didn't mean to insult anyone, forking is a natural part of open source. I am very happy to see that phaazon is back, but i didn't know that. Numerous neovim plugins have been forked for maintenance (lspsaga.nvim, lualine)

If your are objecting to the Reddit post, then that's not on me, if you are objecting to making a fork and/or sharing it. Then that's not how OSS works
